name: Master CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make all

    - name: Test
      run: make test
    
    - name: Get Tag
      id: get_tag
      run: |
        echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
        
    - name: Publish container image
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        TAG=${{ steps.get_tag.outputs.TAG }} make push
